// <auto-generated />
using DVDApi.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DVDApi.Migrations
{
    [DbContext(typeof(DVDContext))]
    partial class DVDContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("DVDApi.Models.DVD", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxDuur")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UitgeverId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("UitgeverId");

                    b.ToTable("DVDs");
                });

            modelBuilder.Entity("DVDApi.Models.Uitgever", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UitgeverNummer")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("Uitgevers");
                });

            modelBuilder.Entity("DVDApi.Models.DVD", b =>
                {
                    b.HasOne("DVDApi.Models.Uitgever", "Uitgever")
                        .WithMany("DVDs")
                        .HasForeignKey("UitgeverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Uitgever");
                });

            modelBuilder.Entity("DVDApi.Models.Uitgever", b =>
                {
                    b.Navigation("DVDs");
                });
#pragma warning restore 612, 618
        }
    }
}
