services:
  y.frontend.prod:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: prod
      args:
        API_URL: "http://localhost:8080"
    ports:
      - 80:80
    depends_on:
      - y.backend.prod
    networks:
      - y
  y.backend.prod:
    build:
      context: ./pb
      dockerfile: dockerfile
    volumes:
      - ./pb/pb_data:/pb/pb_data
      - ./pb/pb_migrations:/pb/pb_migrations
      - ./pb/pb_hooks:/pb/pb_hooks
    ports:
      - 8080:8080
    networks:
      - y
networks:
  y:
    driver: bridge
volumes:
  db:
    driver: local
